apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: sre-demo
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/Bikramgurkha737/aws-eks-terraform-platform.git
    targetRevision: main
    path: helm/sre-demo

    helm:
      valueFiles:
        - ../../gitops/environments/dev/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: sre-demo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true