name: Helm CI

on:
  push:
    branches:
      - main
    paths:
      - "helm/**"
      - ".github/workflows/helm-ci.yml"

  pull_request:
    branches:
      - main
    paths:
      - "helm/**"
      - ".github/workflows/helm-ci.yml"

jobs:
  validate:
    name: Validate Helm Chart
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v4

      - name: Helm Lint
        run: helm lint helm/sre-demo

      - name: Render Helm templates
        run: helm template sre-demo helm/sre-demo > rendered.yaml

      - name: Install Kubeconform
        run: |
          curl -L -o kubeconform.tar.gz \
            https://github.com/yannh/kubeconform/releases/latest/download/kubeconform-linux-amd64.tar.gz
          tar -xzf kubeconform.tar.gz
          sudo mv kubeconform /usr/local/bin/kubeconform

      - name: Validate rendered manifests
        run: kubeconform -strict -summary rendered.yaml